### ISSUE TITLE
Cannot log in with firefox strict setup

### ISSUE THREAD

**Issue by StratusFearMe21** [oasis-sh/oasis#117]
In firefox, if you have strict mode turned on (no third-party cookies). You can't log in with github.

**Comment by StratusFearMe21** [comment]
Firefox says
```
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 
```

**Comment by StratusFearMe21** [comment]
![image](https://user-images.githubusercontent.com/57533634/114719768-6633cc00-9d05-11eb-93b2-bcc73c98189b.png)

**Comment by ShubhamPatilsd** [comment]
I think we have to change firebase auth settings or something

**Comment by yhdesai** [comment]
This might help : https://stackoverflow.com/questions/45880025/firebase-doesnt-work-in-background-script-of-webextension/45902030#45902030

**Comment by samarmohan** [comment]
You can’t log in with GH normally.

**Comment by StratusFearMe21** [comment]
no, I can't unless I switch to chromium

**Comment by f1shy-dev** [comment]
I was thinking about this, and we could use redirect authentication instead

**Comment by StratusFearMe21** [comment]
> I was thinking about this, and we could use redirect authentication instead

I can confirm that many websites do use that, and it works on firefox

**Comment by heybereket** [comment]
This issue has now been resolved and will be usable for the public (on oasis.sh), very soon!
