### ISSUE TITLE
Text not being anchored on the web-page

### ISSUE THREAD

**Issue by acuaroo** [oasis-sh/oasis#142]
** Whats happening**
![image](https://user-images.githubusercontent.com/67112172/115649826-4859fe80-a2e5-11eb-962f-6d549c791479.png)
![image](https://user-images.githubusercontent.com/67112172/115649992-a4bd1e00-a2e5-11eb-8bf3-ba1ba1dc4d93.png)

When resizing or scaling the page up and down, the image is anchored to the bottom, while the text floats around. This causes this visual bug.

** Steps to reproduce **
- 1. Open up oasis.sh, and scroll to the bottom of the page
- 2. Change the browser windows scale vertically to see the effect.

**Comment by Angshu31** [comment]
Thanks for letting us know, I'm fixing it now

**Comment by Angshu31** [comment]
Alright I fixed it
