### ISSUE TITLE
[BUG] Login

### ISSUE THREAD

**Issue by NotReeceHarris** [oasis-sh/oasis#145]
1. An issue with GitHub login callback
2. No function on 'Anon Login'

**Debugging:**
User Agent:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Brave Chrome/90.0.4430.85 Safari/537.36`

**Comment by f1shy-dev** [comment]
Yeah, we haven't finished the implementation of either of those, we're still doing the API first

**Comment by NotReeceHarris** [comment]
ah lol.
