### ISSUE TITLE
feat(api): rate limiting

### ISSUE THREAD

**Issue by bineetNaidu** [oasis-sh/oasis#180]
#### Please Describe The Problem To Be Solved
 **_milestone:_** [Project Card Link](https://github.com/oasis-sh/oasis/projects/2#card-59970428)

Rate limiting is generally put in place as a defensive measure for services. Even highly scalable systems should have limits on consumption at some level. And Also to reduce the cost of collecting Data from firebase (firestore) or The most common reason for rate limiting is to improve the availability of API-based services by avoiding resource starvation. (Dos is prevented)

#### (Optional): Suggest A Solution
- Redis might be an Option for rate limiting

**Comment by Angshu31** [comment]
Don't worry, rate limits are being worked on. Take a look at the [Projects tab](https://github.com/oasis-sh/oasis/projects/2) on GitHub to see the plan.

I will close this issue once rate limiting is fully added

**Comment by bineetNaidu** [comment]
> Don't worry, rate limits are being worked on. Take a look at the [Projects tab](https://github.com/oasis-sh/oasis/projects/2) on GitHub to see the plan.
> 
> I will close this issue once rate limiting is fully added

Just Want to contribute in this awesome project
If there is anything where i can contribute or help :pray: tell me

**Comment by bineetNaidu** [comment]
Aren't anyone working on this?

**Comment by jzeuzs** [comment]
> Aren't anyone working on this?

It isn't priority for now.
