### ISSUE TITLE
feat(setup): setup package

### ISSUE THREAD

**Issue by SamJakob** [oasis-sh/oasis#186]

**Comment by heybereket** [comment]
Would it be the best option to do this in packages/? Or we can make a directory in root called "setup"?

**Comment by Angshu31** [comment]
> Would it be the best option to do this in packages/? Or we can make a directory in root called "setup"?

To be honest, I think that putting it as a package would be the better (and cleaner) choice

**Comment by heybereket** [comment]
> > Would it be the best option to do this in packages/? Or we can make a directory in root called "setup"?
> 
> To be honest, I think that putting it as a package would be the better (and cleaner) choice

Got it, I started setup in [packages/setup](https://github.com/oasis-sh/oasis/tree/staging/packages/setup).
@SamJakob you can continue it from here if you'd like! :)

**Comment by SamJakob** [comment]
Okay, will do.
And yeah I was thinking the package would be cleaner.
