### ISSUE TITLE
feat(api): contributor badge

### ISSUE THREAD

**Issue by heybereket** [oasis-sh/oasis#187]
Check if a user is a contributor on first authentication sign up via GitHub. 
If they are, give them a contributor badge.

**Comment by HenryLeC** [comment]
I don't think this is that useful as a lot of contributors will have already signed up before becoming a contributor.

**Comment by bineetNaidu** [comment]
I don't think so that we will able to access this information. 🤔🤔 we can pull the GitHub API to do so with the help of GitHub id which is stored in our database to query the information

**Comment by Angshu31** [comment]
We will query the GitHub API. We send a simple REST request to see if the user is a contributor. That's how the old oasis worked

**Comment by HenryLeC** [comment]
Yeah but we don't want to do it on every sign in and more likely than not the users wont be contributors on their first sign up

**Comment by HenryLeC** [comment]
We can maybe have a sync badges button on the settings page that will check for new badges?

**Comment by SamJakob** [comment]
We could maybe have a GitHub action to do it on merged PR or something?

**Comment by Angshu31** [comment]
I would suggest an option for the user to apply for the Contributor badge. And then, and only then, we will run that process

**Comment by HenryLeC** [comment]
Yeah we could use webhooks maybe

**Comment by SamJakob** [comment]
> I would suggest an option for the user to apply for the Contributor badge. And then, and only then, we will run that process

Yeah a sorta ‘claim button’ type thing could work

**Comment by Angshu31** [comment]
> > I would suggest an option for the user to apply for the Contributor badge. And then, and only then, we will run that process
> 
> Yeah a sorta ‘claim button’ type thing could work

Yes. Exactly

**Comment by HenryLeC** [comment]
Ok cool, that will work, we could do it in REST. That isn't really a GQL type thing

**Comment by Angshu31** [comment]
> Ok cool, that will work, we could do it in REST. That isn't really a GQL type thing

Yeah. REST is probably the easier choice for this. You can implement that when you want then

**Comment by SamJakob** [comment]
Yeah we should have a REST endpoint group for for automated actions like that I think.

**Comment by Angshu31** [comment]
> Yeah we should have a REST endpoint group for for automated actions like that I think.

Yeah. And the fact that running a GraphQL Mutation for something like this is kind of pointless.

**Comment by HenryLeC** [comment]
Contributor badge now gets picked up on signup and will display on your profile
