### ISSUE TITLE
Feat: Core Markdown Parser Features

### ISSUE THREAD

**Issue by SamJakob** [oasis-sh/oasis#197]
#### Implement the required Markdown parser features for posting

- [ ] Standard text features
  - [ ] Bold
  - [ ] Italic
  - [ ] Underline
  - [ ] Strikethrough

- [ ] Standard Social Features
  - [ ] Links
  - [ ] Images (Do we want this?)

- [ ] Code Highlighting
  - [ ] Code Block (`pre`)
  - [ ] Inline Code (`span`)
  - [ ] Highlighted Code Block

**Comment by BronzW** [comment]
Should this be done with plain text or should it be built with blocks of data?

**Comment by HenryLeC** [comment]
We actually decided on using [react-markdown](https://github.com/remarkjs/react-markdown)
