### ISSUE TITLE
bug(web): safari flex gap

### ISSUE THREAD

**Issue by f1shy-dev** [oasis-sh/oasis#215]
Flex gap doesn't work on safari, making things look weird 
![image](https://user-images.githubusercontent.com/56125930/118050348-fd2c8c00-b376-11eb-9102-530565a77cf8.jpeg)

**Comment by HenryLeC** [comment]
Fixed in #270

**Comment by HenryLeC** [comment]
Hey this was never merged in. I am reopening. If @Simplyalex99 could make a new pr with the fix that would be great.
