### ISSUE TITLE
fix(profile): fix blockquotes

### ISSUE THREAD

**Issue by jzeuzs** [oasis-sh/oasis#303]
#### Issue description
Blockquotes look ugly.

#### Steps to reproduce the issue

1. Go to your profile.
2. Edit it.
3. And put this snippet. 
```md
> Bing Bong
```

#### What's the expected result?
![](https://cdn.tixte.com/uploads/i.tomio.codes/kp3b5p4p69a.png)

#### What's the actual result?
![](https://cdn.tixte.com/uploads/i.tomio.codes/kp3azzmsr9a.png)

**Comment by heybereket** [comment]
Fixed in commit [#1eb8ddb](https://github.com/oasis-sh/oasis/commit/92e1fa3f33fda6ed6a213501a4d0b571d6fa575a)
