### ISSUE TITLE
Bug: post mutations are aborted in firefox

### ISSUE THREAD

**Issue by saihnii4** [oasis-sh/oasis#344]
#### Issue description

Creating a post in Firefox will likely yield an error that is visible in the console but mostly cryptic

#### Steps to reproduce the issue

1. Install Firefox
2. Go to https://dev.oasis.sh
3. Create a post
4. Look at the console and network tab

#### What's the expected result?

A successful mutation and a new post added to my account

#### What's the actual result?

A unsuccessful mutation, no posts, and a cryptic error in the console

#### Additional details / screenshot

I assume it's probably due to Firefox stopping requests after the window reloads, based on this [resource](https://experienceleaguecommunities.adobe.com/t5/adobe-analytics-questions/ns-binding-aborted-error-in-httfox/qaq-p/209435)

The "cryptic error" in the console `NetworkError when attempting to fetch resource`

![Screenshot from 2021-06-01 23-16-24](https://user-images.githubusercontent.com/81787757/120349096-637e4c00-c330-11eb-831c-9294e920e909.png)

**Comment by HenryLeC** [comment]
I suggest instead of navigating on the button press, we add a callback to the mutation that will redirect on success.

**Comment by HenryLeC** [comment]
This was fixed
