### ISSUE TITLE
Bug: State Issues

### ISSUE THREAD

**Issue by clayjens** [oasis-sh/oasis#412]
#### Issue description
Downvotes while in your personal dashboard in the Upvotes tab reset the vote counter to 0.
Switching between Posts and Upvotes tabs resets the state to the previous vote counter.

#### Steps to reproduce the issue
All steps assumed the user is logged in and feed posts have been previous upvoted.

1. Click on the User Avatar and go to the Profile.
2. Go to the Upvotes tab and click the downvote arrow.
3. Switch between Posts & Upvotes and observe the state reset.

#### What's the expected result?

Downvoting a post will remove -1 from the total and remove the post from the Upvotes page.
Switching between Posts and Upvotes will have no effect on each other.

#### What's the actual result?

Downvoting a post will overcount/reset the total state and switching between Posts and Upvotes will also reset the state.

#### Additional details / screenshot
https://drive.google.com/file/d/1-oTKZz54RaQvZufKtlGngTUKfvf4nZdH/view?usp=sharing

**Comment by HenryLeC** [comment]
I can work on this tomorrow or if you want to tackle it you can do that

**Comment by clayjens** [comment]
I've been messing around with the like/dislike issue, and it seems like the mutator for likeDislikePost is called twice. One originator is definitely from line no. 66 in `ui/src/components/profile/Posts`. The other I can only assume is coming somewhere in the chain with the profile/Posts component.
