### ISSUE TITLE
Bad UX in "/new" page

### ISSUE THREAD

**Issue by sudhamjayanthi** [oasis-sh/oasis#66]
### Problem
There's no button to go back to [home ](https://oasis.sh) from the [new project page ](https://oasis.sh/new) which is a bad user experience for a user.

### Solution
Just a simple back button or adding the logo with link to homepage in header.

**Comment by uthmanigbin** [comment]
Yeah, I noticed as well and I'm currently working on the redesign for the navbar and will definitely be adding it.

**Comment by SowinskiMateusz** [comment]
I added link

**Comment by f1shy-dev** [comment]
New design has super-seeded v1, so this is being closed
