### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by coderinblack08** [oasis-sh/oasis#92]
While migrating to next.js and tailwind, we've also decided to create a new design system (in development still).

You can check the file out: [https://www.figma.com/file/XDsIu9yvWZY5MwIm8C46JQ/Oasis-%E2%80%94-Joshua-%F0%9F%8F%9D%EF%B8%8F?node-id=2%3A19](https://www.figma.com/file/XDsIu9yvWZY5MwIm8C46JQ/Oasis-%E2%80%94-Joshua-%F0%9F%8F%9D%EF%B8%8F?node-id=2%3A19)

I'll try to set up storybook.js and implement some of the components.

**Comment by vishy-dev** [comment]
Looks pretty good so far, but maybe we could change up the colours to be a bit more similar to the palette we have right now (not old oasis).

We also added quite a few things to the GUI and features generally so we're going to have to include those too.
