### ISSUE TITLE
feat(web): add the language german

### ISSUE THREAD

**Issue by m2vi** [oasis-sh/oasis#93]
I come from Austria, where they speak German, so to speak. 
So I can add the language if it is considered a good idea to add it.

**Comment by HenryLeC** [comment]
Yeah you can add the German translation, the translation files are in [locales](https://github.com/oasis-sh/oasis/tree/staging/packages/web/public/locales) just copy the English translation file into a new folder for the language code.

**Comment by bineetNaidu** [comment]
> Yeah you can add the German translation, the translation files are in [locales](https://github.com/oasis-sh/oasis/tree/staging/packages/web/public/locales) just copy the English translation file into a new folder for the language code.

The Project looks interesting to me, and looking forward to contribute. Just let you that link to the "locales" folder is broken for some reason.

**Comment by HenryLeC** [comment]
> > Yeah you can add the German translation, the translation files are in [locales](https://github.com/oasis-sh/oasis/tree/staging/packages/web/public/locales) just copy the English translation file into a new folder for the language code.
> 
> 
> 
> The Project looks interesting to me, and looking forward to contribute. Just let you that link to the "locales" folder is broken for some reason.

Yeah sorry the locales folder has been removed for now and should be added back soon. I will let you know once we are excepting translations again.

**Comment by HenryLeC** [comment]
I am going to close this for now as we arent looking for translations right now but I will be sure to ask you when we are
